<a href="https://colab.research.google.com/github/sathya964/113023148045/blob/main/Pandas_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
import numpy as np

data = {
    'transaction_id': range(1, 21),
    'date': pd.date_range('2024-10-01', periods=20, freq='D'),
    'region': ['North', 'South', 'East', 'West', None, 'North', 'South', None, 'East', 'West',
               'North', 'South', 'East', 'West', 'North', None, 'East', 'West', 'North', 'South'],
    'product_category': ['Electronics', 'Clothing', None, 'Books', 'Electronics', 'Home',
                         'Clothing', 'Books', 'Electronics', None, 'Home', 'Clothing',
                         'Books', 'Electronics', 'Home', 'Clothing', 'Books', 'Electronics',
                         'Home', 'Clothing'],
    'sales_amount': [1200, 450, 890, None, 1500, 670, None, 340, 2100, 780,
                     560, None, 420, 1800, 920, 510, 380, None, 1100, 640],
    'quantity': [2, 5, 3, 1, None, 4, 2, 3, 1, 5,
                 3, 2, None, 1, 4, 3, 2, 1, None, 4],
    'customer_age': [25, 34, None, 45, 29, None, 38, 52, 27, 41,
                     33, None, 48, 26, 35, 42, None, 31, 39, 44],
    'payment_method': ['Credit Card', 'UPI', 'Cash', 'Debit Card', 'Credit Card',
                       'UPI', 'Cash', None, 'Credit Card', 'UPI', 'Debit Card',
                       'Cash', 'Credit Card', None, 'UPI', 'Cash', 'Debit Card',
                       'Credit Card', 'UPI', None]
}

df = pd.DataFrame(data)
df

,transaction_id,date,region,product_category,sales_amount,quantity,customer_age,payment_method
0,1,2024-10-01,North,Electronics,1200.0,2.0,25.0,Credit Card
1,2,2024-10-02,South,Clothing,450.0,5.0,34.0,UPI
2,3,2024-10-03,East,None,890.0,3.0,NaN,Cash
3,4,2024-10-04,West,Books,NaN,1.0,45.0,Debit Card
4,5,2024-10-05,None,Electronics,1500.0,NaN,29.0,Credit Card
5,6,2024-10-06,North,Home,670.0,4.0,NaN,UPI
6,7,2024-10-07,South,Clothing,NaN,2.0,38.0,Cash
7,8,2024-10-08,None,Books,340.0,3.0,52.0,None
8,9,2024-10-09,East,Electronics,2100.0,1.0,27.0,Credit Card
9,10,2024-10-10,West,None,780.0,5.0,41.0,UPI
10,11,2024-10-11,North,Home,560.0,3.0,33.0,Debit Card
11,12,2024-10-12,South,Clothing,NaN,2.0,NaN,Cash
12,13,2024-10-13,East,Books,420.0,NaN,48.0,Credit Card
13,14,2024-10-14,West,Electronics,1800.0,1.0,26.0,None
14,15,2024-10-15,North,Home,920.0,4.0,35.0,UPI
15,16,2024-10-16,None,Clothing,510.0,3.0,42.0,Cash
16,17,2024-10-17,East,Books,380.0,2.0,NaN,Debit Card
17,18,2024-10-18,West,Electronics,NaN,1.0,31.0,Credit Card
18,19,2024-10-19,North,Home,1100.0,NaN,39.0,UPI
19,20,2024-10-20,South,Clothing,640.0,4.0,44.0,None

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   transaction_id    20 non-null     int64
 1   date              20 non-null     datetime64[ns]
 2   region            17 non-null     object
 3   product_category  18 non-null     object
 4   sales_amount      16 non-null     float64
 5   quantity          17 non-null     float64
 6   customer_age      16 non-null     float64
 7   payment_method    17 non-null     object
dtypes: datetime64[ns](1), float64(3), int64(1), object(3)
memory usage: 1.4+ KB

In [82]:
df.columns

Index(['transaction_id', 'date', 'region', 'product_category', 'sales_amount',
       'quantity', 'customer_age', 'payment_method'],
      dtype='object')

In [84]:
df.shape

(17, 8)

In [9]:
df.notna().sum()

transaction_id      20
date                20
region              17
product_category    18
sales_amount        16
quantity            17
customer_age        16
payment_method      17
dtype: int64

In [7]:
df.isna().sum()

transaction_id      0
date                0
region              3
product_category    2
sales_amount        4
quantity            3
customer_age        4
payment_method      3
dtype: int64

In [6]:
df.isna().sum().sum()

np.int64(19)

In [27]:
df.mode(axis=1)

/tmp/ipykernel_871/1210916842.py:1: UserWarning: Unable to sort modes: '<' not supported between instances of 'Timestamp' and 'int'
  df.mode(axis=1)

,0,1,2,3,4,5,6,7
0,1,2024-10-01,North,Electronics,1200.0,2.0,25.0,Credit Card
1,2,2024-10-02,South,Clothing,450.0,5.0,34.0,UPI
2,3,NaT,NaN,NaN,NaN,NaN,NaN,NaN
3,4,2024-10-04,West,Books,1.0,45.0,Debit Card,NaN
4,5,2024-10-05,Electronics,1500.0,29.0,Credit Card,NaN,NaN
5,6,2024-10-06,North,Home,670.0,4.0,UPI,NaN
6,7,2024-10-07,South,Clothing,2.0,38.0,Cash,NaN
7,8,2024-10-08,Books,340.0,3.0,52.0,NaN,NaN
8,9,2024-10-09,East,Electronics,2100.0,1.0,27.0,Credit Card
9,10,2024-10-10,West,780.0,5.0,41.0,UPI,NaN
10,11,2024-10-11,North,Home,560.0,3.0,33.0,Debit Card
11,12,2024-10-12,South,Clothing,2.0,Cash,NaN,NaN
12,13,2024-10-13,East,Books,420.0,48.0,Credit Card,NaN
13,14,2024-10-14,West,Electronics,1800.0,1.0,26.0,NaN
14,15,2024-10-15,North,Home,920.0,4.0,35.0,UPI
15,16,2024-10-16,Clothing,510.0,3.0,42.0,Cash,NaN
16,17,2024-10-17,East,Books,380.0,2.0,Debit Card,NaN
17,18,2024-10-18,West,Electronics,1.0,31.0,Credit Card,NaN
18,19,2024-10-19,North,Home,1100.0,39.0,UPI,NaN
19,20,2024-10-20,South,Clothing,640.0,4.0,44.0,NaN

In [32]:
mixed_modes=df[["region","product_category"]].mode()
mixed_modes

  region product_category
0  North         Clothing
1    NaN      Electronics

In [39]:
df

,transaction_id,date,region,product_category,sales_amount,quantity,customer_age,payment_method
0,1,2024-10-01,North,Electronics,1200.0,2.0,25.0,Credit Card
1,2,2024-10-02,South,Clothing,450.0,5.0,34.0,UPI
2,3,2024-10-03,East,None,890.0,3.0,NaN,Cash
3,4,2024-10-04,West,Books,NaN,1.0,45.0,Debit Card
4,5,2024-10-05,None,Electronics,1500.0,NaN,29.0,Credit Card
5,6,2024-10-06,North,Home,670.0,4.0,NaN,UPI
6,7,2024-10-07,South,Clothing,NaN,2.0,38.0,Cash
7,8,2024-10-08,None,Books,340.0,3.0,52.0,None
8,9,2024-10-09,East,Electronics,2100.0,1.0,27.0,Credit Card
9,10,2024-10-10,West,None,780.0,5.0,41.0,UPI
10,11,2024-10-11,North,Home,560.0,3.0,33.0,Debit Card
11,12,2024-10-12,South,Clothing,NaN,2.0,NaN,Cash
12,13,2024-10-13,East,Books,420.0,NaN,48.0,Credit Card
13,14,2024-10-14,West,Electronics,1800.0,1.0,26.0,None
14,15,2024-10-15,North,Home,920.0,4.0,35.0,UPI
15,16,2024-10-16,None,Clothing,510.0,3.0,42.0,Cash
16,17,2024-10-17,East,Books,380.0,2.0,NaN,Debit Card
17,18,2024-10-18,West,Electronics,NaN,1.0,31.0,Credit Card
18,19,2024-10-19,North,Home,1100.0,NaN,39.0,UPI
19,20,2024-10-20,South,Clothing,640.0,4.0,44.0,None

In [44]:
region_mode=df["region"].mode()[0]
product_category_mode=df["product_category"].mode()[0]
print(region_mode)
print(product_category_mode)

North
Clothing

In [46]:
df["region"]=df["region"].fillna(region_mode)
df["product_category"]=df["product_category"].fillna(product_category_mode)
print(df["region"])
print(["product_category"])

0     North
1     South
2      East
3      West
4     North
5     North
6     South
7     North
8      East
9      West
10    North
11    South
12     East
13     West
14    North
15    North
16     East
17     West
18    North
19    South
Name: region, dtype: object
['product_category']

In [47]:
df

,transaction_id,date,region,product_category,sales_amount,quantity,customer_age,payment_method
0,1,2024-10-01,North,Electronics,1200.0,2.0,25.0,Credit Card
1,2,2024-10-02,South,Clothing,450.0,5.0,34.0,UPI
2,3,2024-10-03,East,Clothing,890.0,3.0,NaN,Cash
3,4,2024-10-04,West,Books,NaN,1.0,45.0,Debit Card
4,5,2024-10-05,North,Electronics,1500.0,NaN,29.0,Credit Card
5,6,2024-10-06,North,Home,670.0,4.0,NaN,UPI
6,7,2024-10-07,South,Clothing,NaN,2.0,38.0,Cash
7,8,2024-10-08,North,Books,340.0,3.0,52.0,None
8,9,2024-10-09,East,Electronics,2100.0,1.0,27.0,Credit Card
9,10,2024-10-10,West,Clothing,780.0,5.0,41.0,UPI
10,11,2024-10-11,North,Home,560.0,3.0,33.0,Debit Card
11,12,2024-10-12,South,Clothing,NaN,2.0,NaN,Cash
12,13,2024-10-13,East,Books,420.0,NaN,48.0,Credit Card
13,14,2024-10-14,West,Electronics,1800.0,1.0,26.0,None
14,15,2024-10-15,North,Home,920.0,4.0,35.0,UPI
15,16,2024-10-16,North,Clothing,510.0,3.0,42.0,Cash
16,17,2024-10-17,East,Books,380.0,2.0,NaN,Debit Card
17,18,2024-10-18,West,Electronics,NaN,1.0,31.0,Credit Card
18,19,2024-10-19,North,Home,1100.0,NaN,39.0,UPI
19,20,2024-10-20,South,Clothing,640.0,4.0,44.0,None

In [63]:
sales_amount=df["sales_amount"].median()
df["sales_amount"]=df["sales_amount"].fillna(sales_amount)
print(sales_amount)
print(df["sales_amount"])

890.625
0     1200.00
1      450.00
2      890.00
3      891.25
4     1500.00
5      670.00
6      891.25
7      340.00
8     2100.00
9      780.00
10     560.00
11     891.25
12     420.00
13    1800.00
14     920.00
15     510.00
16     380.00
17     891.25
18    1100.00
19     640.00
Name: sales_amount, dtype: float64

In [58]:
df.isna().sum()

transaction_id      0
date                0
region              0
product_category    0
sales_amount        0
quantity            3
customer_age        4
payment_method      3
dtype: int64

In [59]:
df["quantity"]=df["quantity"].ffill()
print(df["quantity"])

0     2.0
1     5.0
2     3.0
3     1.0
4     1.0
5     4.0
6     2.0
7     3.0
8     1.0
9     5.0
10    3.0
11    2.0
12    2.0
13    1.0
14    4.0
15    3.0
16    2.0
17    1.0
18    1.0
19    4.0
Name: quantity, dtype: float64

In [60]:
df.isna().sum()

transaction_id      0
date                0
region              0
product_category    0
sales_amount        0
quantity            0
customer_age        4
payment_method      3
dtype: int64

In [64]:
customer_age=df["customer_age"].mean()
df["customer_age"]=df["customer_age"].fillna(customer_age)
print(customer_age)
print(df["customer_age"])

36.8125
0     36.8125
1     36.8125
2     36.8125
3     36.8125
4     36.8125
5     36.8125
6     36.8125
7     36.8125
8     36.8125
9     36.8125
10    36.8125
11    36.8125
12    36.8125
13    36.8125
14    36.8125
15    36.8125
16    36.8125
17    36.8125
18    36.8125
19    36.8125
Name: customer_age, dtype: float64

In [65]:
df

,transaction_id,date,region,product_category,sales_amount,quantity,customer_age,payment_method
0,1,2024-10-01,North,Electronics,1200.00,2.0,36.8125,Credit Card
1,2,2024-10-02,South,Clothing,450.00,5.0,36.8125,UPI
2,3,2024-10-03,East,Clothing,890.00,3.0,36.8125,Cash
3,4,2024-10-04,West,Books,891.25,1.0,36.8125,Debit Card
4,5,2024-10-05,North,Electronics,1500.00,1.0,36.8125,Credit Card
5,6,2024-10-06,North,Home,670.00,4.0,36.8125,UPI
6,7,2024-10-07,South,Clothing,891.25,2.0,36.8125,Cash
7,8,2024-10-08,North,Books,340.00,3.0,36.8125,None
8,9,2024-10-09,East,Electronics,2100.00,1.0,36.8125,Credit Card
9,10,2024-10-10,West,Clothing,780.00,5.0,36.8125,UPI
10,11,2024-10-11,North,Home,560.00,3.0,36.8125,Debit Card
11,12,2024-10-12,South,Clothing,891.25,2.0,36.8125,Cash
12,13,2024-10-13,East,Books,420.00,2.0,36.8125,Credit Card
13,14,2024-10-14,West,Electronics,1800.00,1.0,36.8125,None
14,15,2024-10-15,North,Home,920.00,4.0,36.8125,UPI
15,16,2024-10-16,North,Clothing,510.00,3.0,36.8125,Cash
16,17,2024-10-17,East,Books,380.00,2.0,36.8125,Debit Card
17,18,2024-10-18,West,Electronics,891.25,1.0,36.8125,Credit Card
18,19,2024-10-19,North,Home,1100.00,1.0,36.8125,UPI
19,20,2024-10-20,South,Clothing,640.00,4.0,36.8125,None

In [71]:
df.dropna(subset=["payment_method"],inplace=True)

In [72]:
df

,transaction_id,date,region,product_category,sales_amount,quantity,customer_age,payment_method
0,1,2024-10-01,North,Electronics,1200.00,2.0,36.8125,Credit Card
1,2,2024-10-02,South,Clothing,450.00,5.0,36.8125,UPI
2,3,2024-10-03,East,Clothing,890.00,3.0,36.8125,Cash
3,4,2024-10-04,West,Books,891.25,1.0,36.8125,Debit Card
4,5,2024-10-05,North,Electronics,1500.00,1.0,36.8125,Credit Card
5,6,2024-10-06,North,Home,670.00,4.0,36.8125,UPI
6,7,2024-10-07,South,Clothing,891.25,2.0,36.8125,Cash
8,9,2024-10-09,East,Electronics,2100.00,1.0,36.8125,Credit Card
9,10,2024-10-10,West,Clothing,780.00,5.0,36.8125,UPI
10,11,2024-10-11,North,Home,560.00,3.0,36.8125,Debit Card
11,12,2024-10-12,South,Clothing,891.25,2.0,36.8125,Cash
12,13,2024-10-13,East,Books,420.00,2.0,36.8125,Credit Card
14,15,2024-10-15,North,Home,920.00,4.0,36.8125,UPI
15,16,2024-10-16,North,Clothing,510.00,3.0,36.8125,Cash
16,17,2024-10-17,East,Books,380.00,2.0,36.8125,Debit Card
17,18,2024-10-18,West,Electronics,891.25,1.0,36.8125,Credit Card
18,19,2024-10-19,North,Home,1100.00,1.0,36.8125,UPI

In [73]:
df.isna().sum()

transaction_id      0
date                0
region              0
product_category    0
sales_amount        0
quantity            0
customer_age        0
payment_method      0
dtype: int64

In [74]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 17 entries, 0 to 18
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   transaction_id    17 non-null     int64
 1   date              17 non-null     datetime64[ns]
 2   region            17 non-null     object
 3   product_category  17 non-null     object
 4   sales_amount      17 non-null     float64
 5   quantity          17 non-null     float64
 6   customer_age      17 non-null     float64
 7   payment_method    17 non-null     object
dtypes: datetime64[ns](1), float64(3), int64(1), object(3)
memory usage: 1.2+ KB